# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0002_auto_20180502_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_market',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
