# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0004_mysite_market_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite_pricetask',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
