# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0006_auto_20180510_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_community',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='mysite_restaurant',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
