# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0008_mysite_food_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite_food',
            name='food_kind',
        ),
    ]
