# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0010_remove_mysite_food_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysite_pricetask',
            old_name='message_person_id',
            new_name='user_id',
        ),
    ]
