# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0011_auto_20180526_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysite_Market_Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_flow', models.CharField(default=0, max_length=30)),
                ('tanwei_num', models.CharField(default=0, max_length=30)),
                ('tanwei_use_num', models.CharField(default=0, max_length=30)),
            ],
            bases=(models.Model, django.db.models.manager.Manager),
        ),
        migrations.AddField(
            model_name='mysite_market',
            name='people_flow',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='mysite_market',
            name='tanwei_num',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='mysite_market',
            name='tanwei_use_num',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='mysite_market_message',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysite_market_mysite_market_message', to='mygis.Mysite_Market'),
        ),
    ]
