# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0012_auto_20180527_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_market_message',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
