# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0013_mysite_market_message_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite_market_message',
            name='market',
        ),
    ]
