# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygis', '0014_remove_mysite_market_message_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_market_message',
            name='market',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mysite_market_mysite_market_message', to='mygis.Mysite_Market'),
        ),
        migrations.AddField(
            model_name='mysite_market_message',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_mysite_market_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
