# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygis', '0015_auto_20180527_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysite_target',
            old_name='xfws',
            new_name='cpxxcd',
        ),
        migrations.AddField(
            model_name='mysite_target',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mysite_target',
            name='market',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mysite_market_mysite_target', to='mygis.Mysite_Market'),
        ),
        migrations.AddField(
            model_name='mysite_target',
            name='pingfen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mysite_target',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_mysite_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
