# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygis', '0016_auto_20180528_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_market_message',
            name='check',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='mysite_peopletask',
            name='check',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='mysite_pricetask',
            name='check',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='mysite_target',
            name='check',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
